# Generated by Django 4.2 on 2023-04-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.TextField()),
                ('mobile_no', models.IntegerField()),
                ('alt_mobile_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('items', models.TextField()),
                ('vehicle_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.TextField()),
                ('mobile_no', models.IntegerField()),
                ('landline_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
